### ISSUE TITLE
plugin.video.malabartalkies-0.1.8.zip File has addons.xml which specifies 0.1.7

### ISSUE THREAD

**Issue by ktaragorn** [gbzygil/gbzygil-xbmc-repo#1]
I am not sure how kodi addons work in updating, is this the reason for my reason as in http://forum.kodi.tv/showthread.php?tid=183360&page=5 ? 

>Hi I am not sure why.. but I have been stuck in an infinite loop trying to update 0.1.7 -> 0.1.8 for the last few months, every day it attempts to update but then it still shows the version as 0.1.7, so it tries again. This appears to be the only plugin with this issue. Am i doing something wrong? I dont see the "force refresh" function in isengard any more.

**Comment by gbzygil** [comment]
fixed
