### ISSUE TITLE
Thiruttuvcd telugu movie link broken

### ISSUE THREAD

**Issue by shravanpn7** [gbzygil/gbzygil-xbmc-repo#2]
http://www.thiruttuvcd.me/category/telugu/page/1/ is moved to http://www.thiruttuvcd.me/category/watch-telugu-movie/page/1/

I'll submit a pull req if i find time.

**Comment by Gujal00** [comment]
Included in pull request #3 
Dunno if gbzygil is around to accept it

**Comment by gbzygil** [comment]
he is :)

**Comment by Gujal00** [comment]
Nice :+1:
